<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Created At' => '',
    'Galleries' => '',
    'Galleries have been successfully deleted.' => '',
    'Galleries list' => '',
    'Gallery creation' => '',
    'Gallery has been successfully created.' => '',
    'Gallery has been successfully deleted.' => '',
    'Gallery has been successfully saved.' => '',
    'Gallery has not been created. Please try again!' => '',
    'Gallery has not been saved. Please try again!' => '',
    'ID' => '',
    'Inactive' => '',
    'Name' => '',
    'Status' => '',
    'Updated At' => '',
    '{count} galleries have been successfully saved.' => '',
];
