<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Link relationship (XFN)' => '',
    ' Open in a new window/tab' => '',
    'Active' => '',
    'Active icon' => '',
    'CSS classes' => '',
    'Create' => '',
    'Delete' => '',
    'Display' => '',
    'Dropdown' => '',
    'Edit' => '',
    'Full width dropdown' => '',
    'Grid (requires css class for items)' => '',
    'ID' => '',
    'Icon' => '',
    'Inactive' => '',
    'Items CSS classes' => '',
    'Items display' => '',
    'Label' => '',
    'List' => '',
    'Main' => '',
    'Menu item creation' => '',
    'Menu item has been successfully created.' => '',
    'Menu item has been successfully deleted.' => '',
    'Menu item has been successfully saved.' => '',
    'Menu item has not been created. Please try again!' => '',
    'Menu item has not been saved. Please try again!' => '',
    'Menu item updating' => '',
    'Menu items' => '',
    'Menu items have been successfully deleted.' => '',
    'Please, select menu item to delete' => '',
    'Please, select menu item to edit' => '',
    'Status' => '',
    'Title' => '',
    'URL' => '',
    'Video' => '',
    'Visibility' => '',
    '{count} menu items have been successfully saved.' => '',
];
