<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Content' => 'Содержимое',
    'Created At' => 'Дата создания',
    'ID' => 'ID',
    'Meta Description' => 'Мета описание',
    'Meta Title' => 'Мета заголовок',
    'Slug' => 'URL',
    'Title' => 'Заголовок',
    'Updated At' => 'Дата обновления',
    'Status' => 'Статус',
    'Deleted' => 'Удаленная',
    'Unpublished' => 'Неопубликованная',
    'Published' => 'Опубликованная'
];
