<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete selected items?' => '',
    'Batch editing' => '',
    'Close' => '',
    'Code' => '',
    'Content' => '',
    'Content widget' => '',
    'Create' => '',
    'Created At' => '',
    'Custom' => '',
    'Delete selected' => '',
    'Deleted' => '',
    'Display' => '',
    'Don\'t display' => '',
    'Fields to update' => '',
    'ID' => '',
    'Inherit' => '',
    'Layout' => '',
    'Main' => '',
    'Meta information' => '',
    'Open Graph' => '',
    'Page' => '',
    'Page creation' => '',
    'Page has been successfully created.' => '',
    'Page has been successfully deleted.' => '',
    'Page has been successfully saved.' => '',
    'Page has not been created. Please try again!' => '',
    'Page has not been saved. Please try again!' => '',
    'Page updating' => '',
    'Pages' => '',
    'Pages have been successfully deleted.' => '',
    'Parent' => '',
    'Please, select items to delete' => '',
    'Published' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Select all' => '',
    'Select status' => '',
    'Slug' => '',
    'Social Meta Tags' => '',
    'Status' => '',
    'Template' => '',
    'Title' => '',
    'Unpublished' => '',
    'Update' => '',
    'Updated At' => '',
    'Widget for displaying content blocks on the page.' => '',
    '{count} pages have been successfully saved.' => '',
];
