<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Announce' => '',
    'Article creation' => '',
    'Article has been successfully created.' => '',
    'Article has been successfully deleted.' => '',
    'Article has been successfully saved.' => '',
    'Article has not been created. Please try again!' => '',
    'Article has not been saved. Please try again!' => '',
    'Article updating' => '',
    'Articles' => '',
    'Articles have been successfully deleted.' => '',
    'Articles list' => '',
    'Content' => '',
    'Created At' => '',
    'Deleted' => '',
    'Files' => '',
    'ID' => '',
    'Main' => '',
    'News has been successfully created.' => '',
    'News has been successfully deleted.' => '',
    'News has been successfully saved.' => '',
    'News has not been created. Please try again!' => '',
    'News has not been saved. Please try again!' => '',
    'News have been successfully deleted.' => '',
    'Published' => '',
    'Slug' => '',
    'Status' => '',
    'Title' => '',
    'Unpublished' => '',
    'Updated At' => '',
    '{count} articles have been successfully saved.' => '',
    '{count} news have been successfully saved.' => '',
];
