<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'AND' => '',
    'Add value' => '',
    'Attribute name' => '',
    'Attribute name in index' => '',
    'Attribute values as facet values' => '',
    'Custom values' => '',
    'Entity type' => '',
    'Facet creation' => '',
    'Facet has been successfully created.' => '',
    'Facet has been successfully deleted.' => '',
    'Facet has been successfully saved.' => '',
    'Facet updating' => '',
    'Facets' => '',
    'Facets list' => '',
    'From' => '',
    'ID' => '',
    'Interval' => '',
    'Interval facet' => '',
    'Label' => '',
    'Multivalue' => '',
    'Name' => '',
    'OR' => '',
    'Operator' => '',
    'Range' => '',
    'Range facet' => '',
    'Searchable types facet' => '',
    'Searchable types facet term' => '',
    'Term' => '',
    'Terms facet' => '',
    'To' => '',
    'Type' => '',
    'Values' => '',
    'Whether facet can has multiple selected values' => '',
    'Will be used in the search query' => '',
];
